### PR TITLE
Support for Jenkins-compatible JUnit output

### PR DESCRIPTION
**Pull request by cdonahue**
XML output updated to adhere to the Jenkins JUnit xsd document as posted below, in response to issue #92.

While we only list the child failure once per test case, the message notes how many of the iterations actually failed. Using the XML output as generated by these changes allows the "failure" count to display in Jenkins test output and trend charts and validates against the Jenkins JUnit expected xml schema.

First time submitting a pull request, so please let me know if there's anything I can do to help in the future - the Newman project is really quite nice and I think you guys have done a great job with it.

https://svn.jenkins-ci.org/trunk/hudson/dtkit/dtkit-format/dtkit-junit-model/src/main/resources/com/thalesgroup/dtkit/junit/model/xsd/junit-4.xsd

### CODE REVIEW

**Comment by brothhaar** [comment]
+1 for this pull request. I have made similar changes in my own fork that I was going to request before seeing this one.

**Comment by cdonahue** [comment]
Hi all - anything I can do to help get this pull request merged to master?

**Comment by abhijitkane** [comment]
We're a little swamped with Postman-related development right now. We'll take a look at this soon. Thanks!

**Comment by jxf86** [comment]
Are you able to take a look at merging this, or still swamped?

**Comment by brothhaar** [comment]
PLEASE merge this

**Pull request merged**
